language: go
before_install:
- UPDATE_URL="https://appengine.google.com/api/updatecheck"
- VERSION=$(echo $(curl ${UPDATE_URL}) | sed -E 's/release: \"(.+)\"(.*)/\1/g')
 - wget $UPDATE_URL
 - unzip -d $HOME go_appengine_sdk_linux_amd64-*.zip
 - ln -s $HOME/go_appengine/goroot/src/pkg/appengine $HOME/gopath/src/appengine
 - ln -s $HOME/go_appengine/goroot/src/pkg/appengine_internal $HOME/gopath/src/appengine_internal
 - export PATH=$PATH:$HOME/go_appengine
install: 
script: go test
